
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.time;
import java.awt.AWTException;
import java.awt.Robot;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hadielmekawi
 */
public class TimerFrame extends javax.swing.JFrame {

    private Object JTextField1;
    private Object time;

    /**
     * Creates new form TimerFrame
     */
    public TimerFrame() {
        initComponents();
    }

    public void reset() {

        oneSecs.setText("000");
        oneTens.setText("000");
        oneMin.setText("000");
        oneTensMin.setText("000");
        oneHour.setText("000");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        digitValue = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        showDigit = new javax.swing.JButton();
        AddOne = new javax.swing.JButton();
        oneSecsDisplay = new javax.swing.JButton();
        oneSecs = new javax.swing.JTextField();
        ShowOneSecsDisplay = new javax.swing.JButton();
        oneTensDisplay = new javax.swing.JButton();
        ShowTenDisplay = new javax.swing.JButton();
        oneTens = new javax.swing.JTextField();
        oneMinDisplay = new javax.swing.JButton();
        oneMin = new javax.swing.JTextField();
        ShowMinDisplay = new javax.swing.JButton();
        ShowTMdisplay = new javax.swing.JButton();
        oneTensMin = new javax.swing.JTextField();
        oneTensMDisplay = new javax.swing.JButton();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        oneHourDisplay = new javax.swing.JButton();
        ShowHourDisplay = new javax.swing.JButton();
        oneHour = new javax.swing.JTextField();
        StartTimer = new javax.swing.JButton();
        stop = new javax.swing.JButton();
        StartDate = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        TensMT = new javax.swing.JTextField();
        MT = new javax.swing.JTextField();
        TensST = new javax.swing.JTextField();
        ST = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        HT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Pause = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Digital Timer");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        digitValue.setText("000");
        digitValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitValueActionPerformed(evt);
            }
        });
        getContentPane().add(digitValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 40, -1));

        jTextField1.setBackground(new java.awt.Color(0, 51, 255));
        jTextField1.setText("   ");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 30, 80));

        jTextField2.setBackground(new java.awt.Color(0, 51, 255));
        jTextField2.setText("   ");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 30, 100));

        jTextField3.setBackground(new java.awt.Color(0, 51, 255));
        jTextField3.setText("   ");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 110, 30));

        jTextField4.setBackground(new java.awt.Color(0, 51, 255));
        jTextField4.setText("   ");
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 30, 100));

        jTextField5.setBackground(new java.awt.Color(0, 51, 255));
        jTextField5.setText("   ");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 30, 80));

        jTextField6.setBackground(new java.awt.Color(0, 51, 255));
        jTextField6.setText("   ");
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 110, 30));

        jTextField7.setBackground(new java.awt.Color(0, 51, 255));
        jTextField7.setText("   ");
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 110, 30));

        showDigit.setText("show Digits ");
        showDigit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDigitActionPerformed(evt);
            }
        });
        getContentPane().add(showDigit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 120, -1));

        AddOne.setText("Add One");
        AddOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddOneActionPerformed(evt);
            }
        });
        getContentPane().add(AddOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, -1, -1));

        oneSecsDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneSecsDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(oneSecsDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 120, 160));

        oneSecs.setText("000");
        oneSecs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneSecsActionPerformed(evt);
            }
        });
        getContentPane().add(oneSecs, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, -1, -1));

        ShowOneSecsDisplay.setText("ShowOneSecs");
        ShowOneSecsDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowOneSecsDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(ShowOneSecsDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 530, 90, -1));

        oneTensDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneTensDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(oneTensDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 130, 160));

        ShowTenDisplay.setText("ShowTenDisplay");
        ShowTenDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowTenDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(ShowTenDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, 100, -1));

        oneTens.setText("000");
        oneTens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneTensActionPerformed(evt);
            }
        });
        getContentPane().add(oneTens, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 530, 40, -1));

        oneMinDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneMinDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(oneMinDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 130, 160));

        oneMin.setText("000");
        oneMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneMinActionPerformed(evt);
            }
        });
        getContentPane().add(oneMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, 50, -1));

        ShowMinDisplay.setText("ShowMinDisplay");
        ShowMinDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowMinDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(ShowMinDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, 90, -1));

        ShowTMdisplay.setText("ShowTMDispaly");
        ShowTMdisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowTMdisplayActionPerformed(evt);
            }
        });
        getContentPane().add(ShowTMdisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 80, -1));

        oneTensMin.setText("000");
        getContentPane().add(oneTensMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 50, -1));

        oneTensMDisplay.setText(" ");
        oneTensMDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneTensMDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(oneTensMDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 120, 160));

        jTextField14.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, -1, 10));

        jTextField15.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, 10));

        jTextField18.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 430, -1, 10));

        jTextField19.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, -1, 10));

        jTextField21.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, -1, 10));

        oneHourDisplay.setText(" ");
        oneHourDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneHourDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(oneHourDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 120, 160));

        ShowHourDisplay.setText("Showhour");
        ShowHourDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowHourDisplayActionPerformed(evt);
            }
        });
        getContentPane().add(ShowHourDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 90, -1));

        oneHour.setText("000");
        oneHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneHourActionPerformed(evt);
            }
        });
        getContentPane().add(oneHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 50, -1));

        StartTimer.setText("Start Timer");
        StartTimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartTimerActionPerformed(evt);
            }
        });
        getContentPane().add(StartTimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, -1));

        stop.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        stop.setText("x");
        stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopActionPerformed(evt);
            }
        });
        getContentPane().add(stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 80, 100));

        StartDate.setText("Start Date");
        StartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartDateActionPerformed(evt);
            }
        });
        getContentPane().add(StartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, -1));

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, -1));

        TensMT.setText("00");
        getContentPane().add(TensMT, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 40, -1));

        MT.setText("00");
        MT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MTActionPerformed(evt);
            }
        });
        getContentPane().add(MT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 40, -1));

        TensST.setText("00");
        TensST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TensSTActionPerformed(evt);
            }
        });
        getContentPane().add(TensST, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 40, -1));

        ST.setText("00");
        ST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STActionPerformed(evt);
            }
        });
        getContentPane().add(ST, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 40, -1));

        jLabel1.setText("Seconds");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        jLabel2.setText("Minutes");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        HT.setText("00");
        getContentPane().add(HT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 40, -1));

        jLabel3.setText("Hours");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        Pause.setText("Pause");
        Pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PauseActionPerformed(evt);
            }
        });
        getContentPane().add(Pause, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, -1));

        jButton1.setText("Click to stop timer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 210, -1));

        jTextField22.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, 10));

        jTextField23.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, -1, 10));

        jTextField24.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, -1, 10));

        jLabel4.setText("Enter any value, click on Click to stop and wait");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 320, 30));

        jLabel5.setText("Click two times ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 120, -1));

        jLabel6.setText("Reset everything to 0");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 150, -1));

        jLabel7.setText("Pause timer. after click Reset");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 200, -1));

        jLabel8.setText("Strat your timer");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showDigitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDigitActionPerformed
        // TODO add your handling code here:

        int digitl = Integer.parseInt(digitValue.getText());

        if (digitl == 0) {

            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            jTextField4.setVisible(true);
            jTextField5.setVisible(true);
            jTextField6.setVisible(true);
            jTextField7.setVisible(false);
        }

        if (digitl == 1) {

            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(false);
            jTextField4.setVisible(false);
            jTextField5.setVisible(false);
            jTextField6.setVisible(false);
            jTextField7.setVisible(false);

        }
        if (digitl == 2) {

            jTextField1.setVisible(true);
            jTextField2.setVisible(false);
            jTextField3.setVisible(true);
            jTextField4.setVisible(true);
            jTextField5.setVisible(false);
            jTextField6.setVisible(true);
            jTextField7.setVisible(true);

        }

        if (digitl == 3) {

            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            jTextField4.setVisible(false);
            jTextField5.setVisible(false);
            jTextField6.setVisible(true);
            jTextField7.setVisible(true);

        }
        if (digitl == 4) {

            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(false);
            jTextField4.setVisible(false);
            jTextField5.setVisible(true);
            jTextField6.setVisible(false);
            jTextField7.setVisible(true);
        }

        if (digitl == 5) {

            jTextField1.setVisible(false);
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            jTextField4.setVisible(false);
            jTextField5.setVisible(true);
            jTextField6.setVisible(true);
            jTextField7.setVisible(true);
        }

        if (digitl == 6) {

            jTextField1.setVisible(false);
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            jTextField4.setVisible(true);
            jTextField5.setVisible(true);
            jTextField6.setVisible(true);
            jTextField7.setVisible(true);

        }
        if (digitl == 7) {

            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(false);
            jTextField4.setVisible(false);
            jTextField5.setVisible(false);
            jTextField6.setVisible(true);
            jTextField7.setVisible(false);
        }

        if (digitl == 8) {

            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            jTextField4.setVisible(true);
            jTextField5.setVisible(true);
            jTextField6.setVisible(true);
            jTextField7.setVisible(true);
        }
        if (digitl == 9) {

            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            jTextField4.setVisible(false);
            jTextField5.setVisible(true);
            jTextField6.setVisible(true);
            jTextField7.setVisible(true);

        }


    }//GEN-LAST:event_showDigitActionPerformed

    private void AddOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddOneActionPerformed
        // TODO add your handling code here:

        int dd = Integer.parseInt(digitValue.getText()); ///for millisends
        int ones = Integer.parseInt(oneSecs.getText());//for ones seconds
        int tens = Integer.parseInt(oneTens.getText());//for tens seconds
        int mins = Integer.parseInt(oneMin.getText());  //for Minutes
        int tensMin = Integer.parseInt(oneTensMin.getText());// for tens minutes
        int hour = Integer.parseInt(oneHour.getText());// for hours

        ShowOneSecsDisplayActionPerformed(evt);
        ShowTenDisplayActionPerformed(evt);
        ShowMinDisplayActionPerformed(evt);
        ShowTMdisplayActionPerformed(evt);
        ShowHourDisplayActionPerformed(evt);

        dd++;

       
        if (dd == 10) {

            dd = 0;
            ones++;

        }

        if (ones == 10) {

            ones = 0;
            tens++;

        }

        if (tens == 6) {

            tens = 0;
            mins++;

        }

        if (mins == 10) {

            mins = 0;
            tensMin++;

        }

        if (tensMin == 6) {

            tensMin = 0;
            hour++;

        }

        //for milliseconds
        String ss = Integer.toString(dd);
        digitValue.setText(ss);
        showDigitActionPerformed(evt);

        //for seconds
        String s = Integer.toString(ones);
        oneSecs.setText(s);
        ShowOneSecsDisplayActionPerformed(evt);

        //for tens
        String t = Integer.toString(tens);
        oneTens.setText(t);
        oneTensDisplayActionPerformed(evt);

        //for mins
        String m = Integer.toString(mins);
        oneMin.setText(m);
        ShowMinDisplayActionPerformed(evt);

        //for tens min
        String tm = Integer.toString(tensMin);
        oneTensMin.setText(tm);
        ShowTMdisplayActionPerformed(evt);

        //for Hours
        String h = Integer.toString(hour);
        oneHour.setText(h);
        ShowHourDisplayActionPerformed(evt);


    }//GEN-LAST:event_AddOneActionPerformed

    private void oneSecsDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneSecsDisplayActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_oneSecsDisplayActionPerformed

    private void ShowOneSecsDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowOneSecsDisplayActionPerformed
        // TODO add your handling code here:

        int ones = Integer.parseInt(oneSecs.getText());

        if (ones == 0) {
            oneSecsDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/0.png"));

        } else if (ones == 1) {
            oneSecsDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/1.png"));

        } else if (ones == 2) {
            oneSecsDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/2.png"));

        } else if (ones == 3) {
            oneSecsDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/3.png"));

        } else if (ones == 4) {
            oneSecsDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/4.png"));

        } else if (ones == 5) {
            oneSecsDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/5.png"));

        } else if (ones == 6) {
            oneSecsDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/6.png"));

        } else if (ones == 7) {
            oneSecsDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/7.png"));

        } else if (ones == 8) {
            oneSecsDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/8.png"));

        } else if (ones == 9) {
            oneSecsDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/9.png"));

        }


    }//GEN-LAST:event_ShowOneSecsDisplayActionPerformed

    private void oneSecsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneSecsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneSecsActionPerformed

    private void ShowTenDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowTenDisplayActionPerformed

        int tens = Integer.parseInt(oneTens.getText());

        if (tens == 0) {
            oneTensDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/0.png"));

        }

        if (tens == 1) {
            oneTensDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/1.png"));

        }

        if (tens == 2) {
            oneTensDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/2.png"));

        }

        if (tens == 3) {
            oneTensDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/3.png"));

        }

        if (tens == 4) {
            oneTensDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/4.png"));

        }

        if (tens == 5) {
            oneTensDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/5.png"));

        }

        if (tens == 6) {
            oneTensDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/6.png"));

        }

        if (tens == 7) {
            oneTensDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/7.png"));

        }

        if (tens == 8) {
            oneTensDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/8.png"));

        }

        if (tens == 9) {
            oneTensDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/9.png"));

        }


    }//GEN-LAST:event_ShowTenDisplayActionPerformed

    private void oneTensDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneTensDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneTensDisplayActionPerformed

    private void digitValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digitValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_digitValueActionPerformed

    private void ShowMinDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowMinDisplayActionPerformed
        // TODO add your handling code here:
        int mins = Integer.parseInt(oneMin.getText());

        if (mins == 0) {
            oneMinDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/0.png"));

        }

        if (mins == 1) {
            oneMinDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/1.png"));

        }

        if (mins == 2) {
            oneMinDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/2.png"));

        }

        if (mins == 3) {
            oneMinDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/3.png"));

        }

        if (mins == 4) {
            oneMinDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/4.png"));

        }

        if (mins == 5) {
            oneMinDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/5.png"));

        }

        if (mins == 6) {
            oneMinDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/6.png"));

        }

        if (mins == 7) {
            oneMinDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/7.png"));

        }

        if (mins == 8) {
            oneMinDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/8.png"));

        }

        if (mins == 9) {
            oneMinDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/9.png"));

        }


    }//GEN-LAST:event_ShowMinDisplayActionPerformed

    private void oneMinDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneMinDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneMinDisplayActionPerformed

    private void oneTensMDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneTensMDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneTensMDisplayActionPerformed

    private void ShowTMdisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowTMdisplayActionPerformed
        // TODO add your handling code here:

        int tensMin = Integer.parseInt(oneTensMin.getText());

        if (tensMin == 0) {
            oneTensMDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/0.png"));

        }

        if (tensMin == 1) {
            oneTensMDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/1.png"));

        }

        if (tensMin == 2) {
            oneTensMDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/2.png"));

        }

        if (tensMin == 3) {
            oneTensMDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/3.png"));

        }

        if (tensMin == 4) {
            oneTensMDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/4.png"));

        }

        if (tensMin == 5) {
            oneTensMDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/5.png"));

        }

        if (tensMin == 6) {
            oneTensMDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/6.png"));

        }

        if (tensMin == 7) {
            oneTensMDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/7.png"));

        }

        if (tensMin == 8) {
            oneTensMDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/8.png"));

        }

        if (tensMin == 9) {
            oneTensMDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/9.png"));

        }

    }//GEN-LAST:event_ShowTMdisplayActionPerformed

    private void ShowHourDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowHourDisplayActionPerformed
        // TODO add your handling code here:

        int hour = Integer.parseInt(oneHour.getText());

        if (hour == 0) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/0.png"));

        }

        if (hour == 1) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/1.png"));

        }

        if (hour == 2) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/2.png"));

        }

        if (hour == 3) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/3.png"));

        }

        if (hour == 4) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/4.png"));

        }

        if (hour == 5) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/5.png"));

        }

        if (hour == 6) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/6.png"));

        }

        if (hour == 7) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/7.png"));

        }

        if (hour == 8) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/8.png"));

        }

        if (hour == 9) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/9.png"));

        }
    }//GEN-LAST:event_ShowHourDisplayActionPerformed

    private void StartTimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartTimerActionPerformed
        // TODO add your handling code here:

        // keep click on add one button every 100 milliseconds
        javax.swing.Timer tm = new javax.swing.Timer(10, new ActionListener() {

            public void actionPerformed(ActionEvent evt) {

                AddOneActionPerformed(evt);
                    
                // is paused ??
                // no -- do whatever below
                // yes -- dont do them
                
                
                //each variable for each new textfield and each display
                
                int dd1 = Integer.parseInt(oneSecs.getText());
                int sst = Integer.parseInt(ST.getText());
  
                int sstt = Integer.parseInt(oneTens.getText());
                int dd11 = Integer.parseInt(TensST.getText());
                
                
                int sstt1 = Integer.parseInt(oneMin.getText());
                int dd111 = Integer.parseInt(MT.getText());
                
                int sstt2 = Integer.parseInt(oneTensMin.getText());
                int dd112 = Integer.parseInt(TensMT.getText());
                
                int hhtt2 = Integer.parseInt(oneHour.getText());
                int dd122 = Integer.parseInt(HT.getText());
                
                
                
                
                
                
                
               // if statement for user when entered a value into text field
                //if the value entered is the same as the timer on running the timer will stop
                if (stopped == true)
                if (dd1 == sst && sstt==dd11 && sstt1 == dd111 && sstt2 == dd112 && hhtt2 == dd122) {

                   PauseActionPerformed(evt);
                   //boolean equal false as we declare it as true in global
                        stopped = false;
                }
                
                

            }

        });
        tm.start();
        
        
        
        
        
        
        
        
        


    }//GEN-LAST:event_StartTimerActionPerformed

    private void stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopActionPerformed
        // TODO add your handling code here:
        
        
        //exit the program
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_stopActionPerformed

    private void StartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartDateActionPerformed
        // TODO add your handling code here:

   
        Date date = new Date();

        //get current date time with Date()
        int HH = Integer.parseInt(oneHour.getText());//declare variable for hours
        int MM = Integer.parseInt(oneMin.getText());//declare variable for Minutes
      //  int SS = Integer.parseInt(oneSecs.getText());//declare variable for seconds

        DateFormat dateFormatOneSec = new SimpleDateFormat("ss");//get seconds
        DateFormat dateFormatOneMin = new SimpleDateFormat("mm");//get minutes
        DateFormat dateFormatOneHour = new SimpleDateFormat("HH");//get hours

      
        //convert date format to string
        String S = dateFormatOneSec.format(date);
      
        //convert date format to string
        String M = dateFormatOneMin.format(date);
      

        //convert date format to string
        String H = dateFormatOneHour.format(date);
        
        // didnt split the number for hours like minutes and seconds
        oneHour.setText(H);
        //click on hours display
        ShowHourDisplayActionPerformed(evt);
        
        
        //split second into 2 character 0 for the first 1 for second
        char ss = S.charAt(0);
        char ss1 = S.charAt(1);
        
        //split minutes into 2 characters 0 for the first 1 for second
        char mm = M.charAt(0);
        char mm1 = M.charAt(1);
        
        //display the first character into one sec display
        oneSecs.setText(Character.toString(ss1));
        ShowOneSecsDisplayActionPerformed(evt);
        
        //display the second character into the tens display
        oneTens.setText(Character.toString(ss));
        ShowTenDisplayActionPerformed(evt);
        
        //display the first char for minutes into minutes display
        oneMin.setText(Character.toString(mm1));
        ShowMinDisplayActionPerformed(evt);
        
        //display the second char for minutes into minutes display
        oneTensMin.setText(Character.toString(mm));
        ShowTMdisplayActionPerformed(evt);

     

            
               
        
        
        if (HH == 1) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/1.png"));
        }
        if (HH == 2) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/2.png"));

        }
        if (HH == 3) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/3.png"));

        }
        if (HH == 4) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/4.png"));

        }
        if (HH == 5) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/5.png"));

        }
        if (HH == 6) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/6.png"));

        }
        if (HH == 7) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/7.png"));

        }
        if (HH == 8) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/8.png"));

        }
        if (HH == 9) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/9.png"));

        }
        if (HH == 10) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/10.png"));

        }
        if (HH == 11) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/11.png"));

        }
        if (HH == 12) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/12.png"));

        }
        if (HH == 13) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/13.png"));

        }
        if (HH == 14) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/14.png"));

        }
        if (HH == 15) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/15.png"));

        }
        if (HH == 16) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/16.png"));

        }
        if (HH == 17) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/17.png"));

        }
        if (HH == 18) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/18.png"));

        }
        if (HH == 19) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/19.png"));

        }
        if (HH == 20) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/20.png"));

        }
        if (HH == 21) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/21.png"));

        }
        if (HH == 22) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/22.png"));

        }
        if (HH == 23) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/23.png"));

        }
        if (HH == 24) {
            oneHourDisplay.setIcon(new javax.swing.ImageIcon("/Users/hadielmekawi/Desktop/Outlook-2/24.png"));

        }


    }//GEN-LAST:event_StartDateActionPerformed

    private void oneHourDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneHourDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneHourDisplayActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:

        reset();

       // JButton  b = new JButton("Clear");
        //b.addActionListener(new ActionListener(){
        // public void actionPerformed(ActionEvent e){
//      oneHour.setText("000");
        //      oneSecs.setText(null); //or use this
        // }
//});

    }//GEN-LAST:event_resetActionPerformed

    private void TensSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TensSTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TensSTActionPerformed

    private void STActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_STActionPerformed

    private void MTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MTActionPerformed

    private void oneMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneMinActionPerformed

    private void PauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PauseActionPerformed
        // TODO add your handling code here:

        oneSecs.setText(" ");
        oneTens.setText(" ");
        oneMin.setText(" ");
        oneTensMin.setText(" ");
        oneHour.setText(" ");


    }//GEN-LAST:event_PauseActionPerformed

    private void oneTensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneTensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneTensActionPerformed
boolean stopped = false;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       stopped = true;

       


    }//GEN-LAST:event_jButton1ActionPerformed

    private void oneHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneHourActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddOne;
    private javax.swing.JTextField HT;
    private javax.swing.JTextField MT;
    private javax.swing.JButton Pause;
    private javax.swing.JTextField ST;
    private javax.swing.JButton ShowHourDisplay;
    private javax.swing.JButton ShowMinDisplay;
    private javax.swing.JButton ShowOneSecsDisplay;
    private javax.swing.JButton ShowTMdisplay;
    private javax.swing.JButton ShowTenDisplay;
    private javax.swing.JButton StartDate;
    private javax.swing.JButton StartTimer;
    private javax.swing.JTextField TensMT;
    private javax.swing.JTextField TensST;
    private javax.swing.JTextField digitValue;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField oneHour;
    private javax.swing.JButton oneHourDisplay;
    private javax.swing.JTextField oneMin;
    private javax.swing.JButton oneMinDisplay;
    private javax.swing.JTextField oneSecs;
    private javax.swing.JButton oneSecsDisplay;
    private javax.swing.JTextField oneTens;
    private javax.swing.JButton oneTensDisplay;
    private javax.swing.JButton oneTensMDisplay;
    private javax.swing.JTextField oneTensMin;
    private javax.swing.JButton reset;
    private javax.swing.JButton showDigit;
    private javax.swing.JButton stop;
    // End of variables declaration//GEN-END:variables
}
